# 1 Homework
## 1.2 Write a Jupyter Magic

In [1]:
from IPython.core.magic import (register_line_magic, register_cell_magic,
                                register_line_cell_magic)

@register_line_cell_magic
def lmagic(line, cell=None):
    if cell is None:
        return len(line.split())
    else:
        return len((line + cell).split())

In [2]:
%lmagic this is a line magic

5

In [3]:
%%lmagic

wow
this is a cell

5

## 1.3 Profile the speed of list comprehension vs. for loops

In [4]:
%%time
list = []
for i in range(100000):
    list.append(i)


Wall time: 11 ms


In [5]:
%time ist2 = [i for i in range(100000)]


Wall time: 3 ms


## 1.4 Prime numbers

In [6]:
def prime_num(l:list):
     return [x for x in l if x >1 and all(x % z != 0 for z in range(2,x))]
prime_num(range(100))

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

## 1.5 Extend the Vector class

In [7]:
import numpy as np
class nVector:
    def __init__(self, *args):
        self.data = np.array(args)
        self.dim = len(args)
        
    def __repr__(self):
        return f"nVector{self.data}"
    
    def __str__(self):
        return f"{self.data}"
    
    def __getitem__(self,key):
        if isinstance(key,int):
            return self.data[key]
        elif isinstance(key,slice):
            return nVector(*(self.data[key]))
        else:
            print("wrong input")
            return
    def __len__(self):
        return self.dim
    
    def __add__(self,other):
        if(self.dim == other.dim):
            return nVector(*(self.data+other.data))
        else:
            print("The dimemsion of the two vectors not same!")
            return 
        
    def __sub__(self,other):
        if(self.dim == other.dim):
            return nVector(*(self.data-other.data))
        else:
            print("The dimemsion of the two vectors not same!")
            return    
        
        
    def __mul__(self,scalar):
        return nVector(*(i * scalar for i in self.data))
    
    def __pow__(self,scalar):
        return nVector(*(i ** scalar for i in self.data))
        
   


In [8]:
vec = nVector(1,2,3,4,5)
vec2 = nVector(2,2,2,2,2)
vec3 = nVector(3,3,3)

print(vec)

print(vec[2])


print(vec[1:3])

print(len(vec))

print(vec+vec2)
print(vec+vec3)
print(vec-vec2)

print(vec*5)
print(vec**2)

[1 2 3 4 5]
3
[2 3]
5
[3 4 5 6 7]
The dimemsion of the two vectors not same!
None
[-1  0  1  2  3]
[ 5 10 15 20 25]
[ 1  4  9 16 25]


## 1.6 Case-insensitive dictionary

In [9]:
class CaseInsensitiveDict(dict):

    class Key(str):
        def __init__(self, key):
            str.__init__(key)
        def __hash__(self):
            return hash(self.lower())
        def __eq__(self, other):
            return self.lower() == other.lower()

    def __init__(self, data=None):
        super(CaseInsensitiveDict, self).__init__()
        if data is None:
            data = {}
        for key, val in data.items():
            self[key] = val
            
    def __contains__(self, key):
        key = self.Key(key)
        return super(CaseInsensitiveDict, self).__contains__(key)
    
    def __setitem__(self, key, value):
        key = self.Key(key)
        super(CaseInsensitiveDict, self).__setitem__(key, value)
        
    def __getitem__(self, key):
        key = self.Key(key)
        return super(CaseInsensitiveDict, self).__getitem__(key)

In [10]:
d = CaseInsensitiveDict()
d['A'] = 3
print(d['a'])

d['A'] = 4
print(d['a'])

print(d)

3
4
{'A': 4}
